obj-$(CONFIG_TOUCHSCREEN_ILITEK) += ilitek.o
ilitek-y += \
	ilitek_def.o \
	ilitek_main.o \
	ilitek_platform_init.o \
	ilitek_update.o \
	ilitek_tool.o \
	ilitek_protocol.o \
	ilitek_crypto.o \
	ilitek_report.o
